### ISSUE TITLE
Error in Setup default notification

### ISSUE THREAD

**Issue by M425** [hpcloud-mon/ansible-monasca-default-alarms#21]
Hi, i'm carrying out this role as part of the repository [monasca-installer](https://github.com/hpcloud-mon/monasca-installer), using single node monasca, and vagrant.

This issue come up:

```
  PLAY [Configure standard alarm definitions] *********************************** 

TASK: [monasca-default-alarms | Setup default notification method] ************ 

<192.168.10.6> ESTABLISH CONNECTION FOR USER: vagrant
<192.168.10.6> REMOTE_MODULE monasca_notification_method type=WEBHOOK address=192.168.10.1:25490/api/callback keystone_password=password keystone_project=test keystone_url=http://192.168.10.5:35357/v3 keystone_user=mini-mon name='Default webhook'
<192.168.10.6> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/home/mat/.ansible/cp/ansible-ssh-%h-%p-%r" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentic
ation=no -o User=vagrant -o ConnectTimeout=10 192.168.10.6 /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1443773236.3-101370438204433 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1443773236.3-101370438204433 && echo $HOME/.ansible/tmp/ansible-tmp-1443773236.3-101370
438204433'
<192.168.10.6> PUT /tmp/tmp7e1a_a TO /home/vagrant/.ansible/tmp/ansible-tmp-1443773236.3-101370438204433/monasca_notification_method
<192.168.10.6> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/home/mat/.ansible/cp/ansible-ssh-%h-%p-%r" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthenti$ation=no -o User=vagrant -o ConnectTimeout=10 192.168.10.6 /bin/sh -c 'LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /home/vagrant/.ansible/tmp/ansible-tmp-1443773236.3-101370438204433/monasca_notification_method; rm -rf /home/vagrant/.ansible/tmp/ansible-tmp-144$773236.3-101370438204433/ >/dev/null 2>&1'

failed: [192.168.10.6] => {"failed": true, "parsed": false}
Traceback (most recent call last):
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1443773236.3-101370438204433/monasca_notification_method", line 1822, in <module>
    main()
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1443773236.3-101370438204433/monasca_notification_method", line 1818, in main
    notification.run()
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1443773236.3-101370438204433/monasca_notification_method", line 1771, in run
    notifications = {notif['name']:notif for notif in self.monasca.notifications.list()}
  File "/usr/local/lib/python2.7/dist-packages/monascaclient/v2_0/notifications.py", line 55, in list
    headers=newheaders)
  File "/usr/local/lib/python2.7/dist-packages/monascaclient/common/http.py", line 295, in json_request
    resp = self._http_request(url, method, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/monascaclient/common/http.py", line 219, in _http_request
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', error(111, 'Connection refused'))
OpenSSH_6.6.1, OpenSSL 1.0.1f 6 Jan 2014
debug1: Reading configuration data /home/mat/.ssh/config
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug1: auto-mux: Trying existing master
debug2: fd 3 setting O_NONBLOCK
debug2: mux_client_hello_exchange: master version 4
debug3: mux_client_forwards: request forwardings: 0 local, 0 remote
debug3: mux_client_request_session: entering
debug3: mux_client_request_alive: entering
debug3: mux_client_request_alive: done pid = 12147
debug3: mux_client_request_session: session request sent
debug1: mux_client_request_session: master session id: 2
debug3: mux_client_read_packet: read header failed: Broken pipe
debug2: Received exit status from master 0
Shared connection to 192.168.10.6 closed.
```

I build the `defaults/main.yml` file in this way:

```
notification_address: 192.168.10.1:25490/api/callback
notification_name: 'Default webhook'
notification_type: WEBHOOK
keystone_project:
```

I have an active http server which debugs out everything arrives (just to study monasca). By connecting ssh i can hit that api correctly.

**Comment by M425** [comment]
it was actually a port mismatch problem. The port used in the monasca-installer repo is the 8080, but the default one in this repo is 8070, and the monasca-installer build script doesn't overwrite correctly the port.
